name: Get Others

# Controls when the workflow will run
on:
  schedule:
    - cron: '00 20 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Run downloader
        run: |
          cd grabber
          npm i
          node index.js

      - name: Write last run time
        run: |
          rm -f _data/bugle.yaml
          echo "date: $(date)" >> _data/bugle.yaml
          rm -f _data/nstaaf.yaml
          echo "date: $(date)" >> _data/nstaaf.yaml

      - name: Commit downloads
        run: |
          ls
          git add *.mp3
          git add *.yaml
          git config --global user.name 'Poddy'
          git config --global user.email 'poddy@users.noreply.github.com'
          git commit -am "Pod grab"
          git push
    
